name: baremetal_ti_am6254_multicore_nosdk

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  target-aarch64-none-elf-gcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install aarch64-none-elf-gcc Toolchain
        run: |
          sudo mkdir -p /arm-toolchain
          wget https://developer.arm.com/-/media/Files/downloads/gnu/14.3.rel1/binrel/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf.tar.xz
          sudo tar -xf arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf.tar.xz -C /arm-toolchain

      - name: Verify Toolchain Installation
        run: |
          sudo ls -la /arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf/bin
          sudo find /arm-toolchain -name aarch64-none-elf-gcc

      - name: Add arm Toolchain to PATH
        run: |
          echo "ARM_TOOLCHAIN=/arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf/bin/" >> $GITHUB_ENV
          echo "PATH=ARM_TOOLCHAIN:$PATH" >> $GITHUB_ENV

      - name: Verify PATH and Check aarch64-none-elf-gcc
        run: |
          echo "Current PATH: $PATH"
          echo "ARM_TOOLCHAIN: $ARM_TOOLCHAIN"
          which aarch64-none-elf-gcc || echo "aarch64-none-elf-gcc not found"

      - name: Verify PATH in a New Step
        run: |
          echo "Updated PATH: $PATH"
          which aarch64-none-elf-gcc || echo "aarch64-none-elf-gcc not found"

      - name: Run Rebuild with Absolute Path
        env:
          GITHUB_ACTIONS: true
        run: |
          /arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-gcc --version
          cd ./Build
          export PATH=/arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf/bin/:$PATH
          sudo chmod +x ./Rebuild.sh
          ./Rebuild.sh a53
