name: baremetal_ti_am6254_multicore_nosdk

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  target-aarch64-none-elf-gcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Install aarch64-none-elf-gcc Toolchain
        run: |
          sudo mkdir -p /arm-toolchain
          wget https://developer.arm.com/-/media/Files/downloads/gnu/14.3.rel1/binrel/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf.tar.xz
          wget https://developer.arm.com/-/media/Files/downloads/gnu/14.3.rel1/binrel/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi.tar.xz
          sudo tar -xf arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf.tar.xz -C /arm-toolchain
          sudo tar -xf arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi.tar.xz -C /arm-toolchain

      - name: Run Rebuild with Absolute Path Added
        env:
          GITHUB_ACTIONS: true
        run: |
          echo "Query toolchain version aarch64-none-elf"
          /arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf/bin/aarch64-none-elf-g++ --version
          /arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi/bin/arn-none-eabi-g++ --version
          cd ./Build
          echo
          echo "Add toolchain absolute paths"
          export PATH=/arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-aarch64-none-elf/bin/:$PATH
          export PATH=/arm-toolchain/arm-gnu-toolchain-14.3.rel1-x86_64-arm-none-eabi/bin/:$PATH
          sudo chmod +x ./Rebuild.sh
          echo
          echo "Rebuild all core binaries"
          ./Rebuild.sh a53
          ./Rebuild.sh m4f
          ./Rebuild.sh r5f
          echo
          echo "Verifiy presence of all core binaries"
          ls -la ../Output/a53_baremetal_am6254_nosdk.bin ../Output/m4f_baremetal_am6254_nosdk.bin ../Output/r5f_baremetal_am6254_nosdk.bin
